#include<iostream>
#include<stdio.h>
using namespace std;
int main()
{
    freopen("in.txt","r",stdin);
    int tc,b,p,f,h,c,pro=0;
    cin>>tc;
    while(tc--)
    {
        cin>>b>>p>>f>>h>>c;
        if(h>c)
        {
            if(p*2<=b)
            {
                b-=(p*2);
                pro+=(h*p);
            }
            else
            {
                if(b%2==0)
                {
                    pro+=((b/2)*h);
                    b=0;
                }
                else
                {
                    pro+=(((b-1)/2)*h);
                    b=1;
                }
            }
            if(b>1)
            {
                if(f*2<=b)
                {
                    b-=(f*2);
                    pro+=(f*c);
                }
                else
                {
                    if(b%2==0)
                    {
                        pro+=((b/2)*c);
                        b=0;
                    }
                    else
                    {
                        pro+=(((b-1)/2)*c);
                        b=1;
                    }
                }
            }
            cout<<pro<<endl;
        }
        else if(h<c)
        {
            if(f*2<=b)
            {
                b-=(f*2);
                pro+=(f*c);
            }
            else
            {
                if(b%2==0)
                {
                    pro+=((b/2)*c);
                    b=0;
                }
                else
                {
                    pro+=(((b-1)/2)*c);
                    b=1;
                }
            }
            if(b>1)
            {
                if(p*2<=b)
                {
                    b-=(p*2);
                    pro+=(p*h);
                }
                else
                {
                    if(b%2==0)
                    {
                        pro+=((b/2)*h);
                        b=0;
                    }
                    else
                    {
                        pro+=(((b-1)/2)*h);
                        b=1;
                    }
                }
            }
            cout<<pro<<endl;
        }
        else if(h==c)
        {
            if(p>f)
            {
                if(p*2<=b)
                {
                    b-=(p*2);
                    pro+=(h*p);
                }
                else
                {
                    if(b%2==0)
                    {
                        pro+=((b/2)*h);
                        b=0;
                    }
                    else
                    {
                        pro+=(((b-1)/2)*h);
                        b=1;
                    }
                }
                if(b>1)
                {
                    if(f*2<=b)
                    {
                        b-=(f*2);
                        pro+=(f*c);
                    }
                    else
                    {
                        if(b%2==0)
                        {
                            pro+=((b/2)*c);
                            b=0;
                        }
                        else
                        {
                            pro+=(((b-1)/2)*c);
                            b=1;
                        }
                    }
                }
                cout<<pro<<endl;
            }
            else
            {
                if(f*2<=b)
                {
                    b-=(f*2);
                    pro+=(f*c);
                }
                else
                {
                    if(b%2==0)
                    {
                        pro+=((b/2)*c);
                        b=0;
                    }
                    else
                    {
                        pro+=(((b-1)/2)*c);
                        b=1;
                    }
                }
                if(b>1)
                {
                    if(p*2<=b)
                    {
                        b-=(p*2);
                        pro+=(p*h);
                    }
                    else
                    {
                        if(b%2==0)
                        {
                            pro+=((b/2)*h);
                            b=0;
                        }
                        else
                        {
                            pro+=(((b-1)/2)*h);
                            b=1;
                        }
                    }
                }
                cout<<pro<<endl;
            }
        }
        pro=0;
    }
    return 0;
}
